version: 3
services:
  db:
    image: postgres:11
    ports:
      - 32700:5432
    volume:
      - ./data/var/lib/postgresql/data
    enviroment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employment_exchange
      